@echo off
echo 正在修复Cursor的MCP配置...
echo {> "C:\Users\13926\.cursor\mcp.json"
echo   "mcpServers": {>> "C:\Users\13926\.cursor\mcp.json"
echo     "memory": {>> "C:\Users\13926\.cursor\mcp.json"
echo       "command": "cmd",>> "C:\Users\13926\.cursor\mcp.json"
echo       "args": [>> "C:\Users\13926\.cursor\mcp.json"
echo         "/c",>> "C:\Users\13926\.cursor\mcp.json"
echo         "npx",>> "C:\Users\13926\.cursor\mcp.json"
echo         "-y",>> "C:\Users\13926\.cursor\mcp.json"
echo         "@modelcontextprotocol/server-memory">> "C:\Users\13926\.cursor\mcp.json"
echo       ],>> "C:\Users\13926\.cursor\mcp.json"
echo       "env": {}>> "C:\Users\13926\.cursor\mcp.json"
echo     },>> "C:\Users\13926\.cursor\mcp.json"
echo     "sequential-thinking": {>> "C:\Users\13926\.cursor\mcp.json"
echo       "command": "cmd",>> "C:\Users\13926\.cursor\mcp.json"
echo       "args": [>> "C:\Users\13926\.cursor\mcp.json"
echo         "/c",>> "C:\Users\13926\.cursor\mcp.json"
echo         "npx",>> "C:\Users\13926\.cursor\mcp.json"
echo         "-y",>> "C:\Users\13926\.cursor\mcp.json"
echo         "@modelcontextprotocol/server-sequential-thinking">> "C:\Users\13926\.cursor\mcp.json"
echo       ],>> "C:\Users\13926\.cursor\mcp.json"
echo       "env": {}>> "C:\Users\13926\.cursor\mcp.json"
echo     }>> "C:\Users\13926\.cursor\mcp.json"
echo   }>> "C:\Users\13926\.cursor\mcp.json"
echo }>> "C:\Users\13926\.cursor\mcp.json"
echo MCP配置已成功修复
pause 